config/routes.rb
Rails.application.routes.draw do

  apipie
	root 'dashboard#index'
  resources :editions do
    resources :lectures
    resources :rooms
  end
  resources :speakers
  resources :collaborators
  resources :collaborator_types
  delete '/speakers/remove_image/:id' => 'speakers#remove_image', as: :remove_image

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
	validates :name, :description, :start_time, :end_time, presence:true
  belongs_to :edition
  belongs_to :speaker
  belongs_to :room

  validates_datetime  :end_time, :on_or_after => :start_time

  def to_s
    name
  end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:name, :description, :start_time, :end_time, :room_id, :speaker_id)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.haml
= simple_form_for(@lecture) do |f|
  = f.error_notification

  .form-inputs

    = f.input :name
    = f.input :description 
    = f.input :start_time
    = f.input :end_time  
    = f.association :speaker, label_method: :last_name,  as: :select
    = f.association :room,  as: :select

  .form-actions
    = f.button :submit

app/views/lectures/edit.html.haml
%h1= t'.title'

= render 'form'

= link_to t("actions.show"), @lecture
\|
= link_to t("actions.back"), lectures_path

app/views/lectures/index.html.haml
%h1= t ".title" 

%table.table.table-striped.table-hover
  %thead
    %tr
      %th= Lecture.human_attribute_name("name")
      %th= Lecture.human_attribute_name("description")
      %th= Lecture.human_attribute_name("start_time")
      %th= Lecture.human_attribute_name("end_time")
      %th= Lecture.human_attribute_name("speaker")
      %th= Lecture.human_attribute_name("room")

      
  %tbody
    - @lectures.each do |lecture|
      %tr
        %td= link_to lecture.name, edition_lecture_path(params[:edition_id], lecture)
        %td= lecture.description
        %td= lecture.start_time
        %td= lecture.end_time
        %td= lecture.speaker(:last_name)
        %td= lecture.room
        %td= link_to t('actions.edit'), edit_edition_lecture_path(params[:edition_id],lecture)
        %td= link_to t('actions.destroy'), edition_lecture_path(params[:edition_id],lecture), :method => :delete, :data => { :confirm => t('actions.confirm') }

%br

= link_to t('actions.new_f'), new_edition_lecture_path(params[:edition_id])

app/views/lectures/new.html.haml
%h1= t".title"

= render 'form'

= link_to t('actions.back'), edition_lecture_path

app/views/lectures/show.html.haml
%p#notice= notice

%p
  %b= t ('lectures.name')
  = @lecture.name
%p
  %b= t('lectures.description')
  = @lecture.description
%p
  %b= t('lectures.start_time')
  = @lecture.start_time
%p
  %b= t('lectures.end_time')
  = @lecture.end_time
%p
  %b= t('lectures.speaker')
  = @lecture.speaker(:last_name)
%p
  %b= t('lectures.room')
  = @lecture.room  

= link_to t('actions.edit'), edit_edition_lecture_path(params[:edition_id], @lecture)
\|
= link_to t('actions.back'), edition_lecture_path