config/routes.rb
Rails.application.routes.draw do

  apipie
	root 'dashboard#index'
  resources :editions do
    resources :lectures
    resources :rooms
  end
  resources :speakers
  resources :collaborators
  resources :collaborator_types
  delete '/speakers/remove_image/:id' => 'speakers#remove_image', as: :remove_image

end

app/models/room.rb
class Room < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
  has_many :lectures


  def to_s
    name
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
= simple_form_for(@room) do |f|
  = f.error_notification

  .form-inputs
  
    = f.input :name 

  .form-actions
    = f.button :submit

app/views/rooms/edit.html.haml
%h1= t(".title")

= render 'form'

= link_to t('actions.edit'), @room
\|
= link_to t('actions.back'), edition_rooms_path

app/views/rooms/index.html.haml
%h1= t".title"

%table.table.table-striped.table-hover
  %thead
    %tr
      %th= Room.human_attribute_name("name")
      %th
      %th

  %tbody
    - @rooms.each do |room|
      %tr
        %td= link_to room.name, edition_room_path(params[:edition_id], room)
        %td= link_to t('actions.edit'), edit_edition_room_path(params[:edition_id],room) 
        %td= link_to t('actions.destroy'), edition_room_path(params[:edition_id],room), :method => :delete, :data => { :confirm => t('actions.confirm') }

%br

= link_to t('actions.new_f'), new_edition_room_path(params[:edition_id])

app/views/rooms/new.html.haml
%h1= t".title"

= render 'form'

= link_to t('actions.back'), edition_room_path

app/views/rooms/show.html.haml
%p#notice= notice

%p
  %b= t ('rooms.name')
  = @room.name
%p
= link_to t('actions.edit'), edit_edition_room_path(params[:edition_id], @room)
\|
= link_to t('actions.back'), edition_rooms_path