config/routes.rb
Rails.application.routes.draw do

  apipie
	root 'dashboard#index'
  resources :editions do
    resources :lectures
    resources :rooms
  end
  resources :speakers
  resources :collaborators
  resources :collaborator_types
  delete '/speakers/remove_image/:id' => 'speakers#remove_image', as: :remove_image

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base

  
	validates :first_name, :last_name, presence: true
  has_many :lectures
  has_attached_file :image, styles: { 
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "640x380>" 
    }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

 def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_action :set_speaker, only: [:show, :edit, :update, :destroy]

  # GET /speakers
  # GET /speakers.json
  def index
    @speakers = Speaker.all
  end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
  end

  # GET /speakers/new
  def new
    @speaker = Speaker.new
  end

  # GET /speakers/1/edit
  def edit
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @speaker = Speaker.new(speaker_params)

    respond_to do |format|
      if @speaker.save
        format.html { redirect_to @speaker, notice: 'Speaker was successfully created.' }
        format.json { render :show, status: :created, location: @speaker }
      else
        format.html { render :new }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speakers/1
  # PATCH/PUT /speakers/1.json
  def update
    



    respond_to do |format|
      if @speaker.update(speaker_params)
        format.html { redirect_to @speaker, notice: 'Speaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @speaker }
      else
        format.html { render :edit }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker.destroy
    respond_to do |format|
      format.html { redirect_to speakers_url, notice: 'Speaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_image     
   speaker = Speaker.where(id: params[:id]).first 
   speaker.image.destroy
   redirect_to request.referer
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speaker
      @speaker = Speaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speaker_params
      params.require(:speaker).permit(:first_name, :nickname, :last_name, :description, :image)
    end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/_form.html.haml
= simple_form_for(@speaker) do |f|
  = f.error_notification
  .form-inputs
    = f.input :first_name
    = f.input :nickname
    = f.input :last_name
    = f.input :description
    = f.input :image
  - if @speaker.image.exists?
    = image_tag @speaker.image.url(:medium)
    = link_to "Remove Image", remove_image_path(@speaker), method: :delete

    
    
  .form-actions
    = f.button :submit

app/views/speakers/edit.html.haml
%h1= t".title"

= render 'form'

= link_to t('actions.edit'), @speaker
\|
= link_to t('actions.back'), speakers_path

app/views/speakers/index.html.haml
%h1= t ".title" 

%table.table.table-striped.table-hover
  %thead
    %tr
      %th= Speaker.human_attribute_name("first_name")
      %th= Speaker.human_attribute_name("nickname")
      %th= Speaker.human_attribute_name("last_name")
      %th= Speaker.human_attribute_name("description")
     

  %tbody
    - @speakers.each do |speaker|
      %tr
        %td= link_to speaker.first_name, speaker
        %td= speaker.nickname
        %td= speaker.last_name
        %td= speaker.description
        %td= link_to t('actions.edit'), edit_speaker_path(speaker)
        %td= link_to t('actions.destroy'), speaker, :method => :delete, :data => { :confirm => t('actions.confirm') }

%br

= link_to t('actions.new'), new_speaker_path

app/views/speakers/new.html.haml
%h1= t".title"

= render 'form'

= link_to t('actions.back'), speakers_path

app/views/speakers/show.html.haml
%p#notice= notice

%p
  %b= t('speakers.first_name')
  = @speaker.first_name
%p
  %b= t('speakers.nickname')
  = @speaker.nickname
%p
  %b= t('speakers.last_name')
  = @speaker.last_name
%p
  %b= t('speakers.description')
  = @speaker.description
%p
  %b= t('speakers.image')
  = image_tag @speaker.image(:medium)




= link_to t('actions.edit'), edit_speaker_path(@speaker)
\|
= link_to t('actions.back'), speakers_path