config/routes.rb
Rails.application.routes.draw do

  apipie
	root 'dashboard#index'
  resources :editions do
    resources :lectures
    resources :rooms
  end
  resources :speakers
  resources :collaborators
  resources :collaborator_types
  delete '/speakers/remove_image/:id' => 'speakers#remove_image', as: :remove_image

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Backend", root_path, class:"navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
       
        %li= link_to t('headers.collaborator_types'), collaborator_types_path
        %li= link_to t('headers.collaborators'), collaborators_path
        %li= link_to t('headers.editions'), editions_path
        %li= link_to t('headers.speakers'), speakers_path
        -if controller_name == "editions" and params[:id]
          %li= link_to t("headers.lectures"), edition_lectures_path(params[:id])
          %li= link_to t("headers.rooms"), edition_rooms_path(params[:id])
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Backend
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'

  .container
    = yield